// all courses must be stored as an array of JSON objects to be passed to the VUE app
const lessons = [
    {
      id: 101,
      title: "Introduction to Library Practices",
      subject: "Programming",
      location: "Online",
      price: 100,
      spaces: 5,
      icon: "bi bi-book",
    },
    {
      id: 102,
      title: "Social media marketing",
      subject: "Programming",
      location: "Online",
      price: 20,
      spaces: 5,
      icon: "bi bi-facebook",
    },
    {
      id: 103,
      title: "Videography and Filming",
      subject: "Programming",
      location: "In-Person",
      price: 30,
      spaces: 5,
      icon: "bi bi-camera",
    },
    {
      id: 104,
      title: 'Intro to drop hipping',
      subject: "Web Development",
      location: "Online",
      price: 25,
      spaces: 5,
      icon: "bi bi-amazon",
    },
    {
      id: 105,
      title: "Intro to Aviation",
      subject: "Web Development",
      location: "In-Person",
      price: 30,
      spaces: 5,
      icon: "bi bi-airplane",
    },
    {
      id: 106,
      title: "Car Racing and Drifting",
      subject: "Web Development",
      location: "Online",
      price: 20,
      spaces: 5,
      icon: "bi bi-speedometer2",
    },
    {
      id: 107,
      title: "First Aid for Beginners",
      subject: "Database",
      location: "In-Person",
      price: 25,
      spaces: 5,
      icon: "bi bi-hospital",
    },
    {
      id: 108,
      title: "Simple accounting techniques",
      subject: "Programming",
      location: "Online",
      price: 35,
      spaces: 5,
      icon: "bi bi-bank",
    },
    {
      id: 109,
      title: "Web Development Best Practices",
      subject: "Web Development",
      location: "In-Person",
      price: 30,
      spaces: 5,
      icon: "bi bi-laptop",
    },
    {
      id: 110,
      title: "Introduction to Cycling",
      subject: "Web Development",
      location: "Online",
      price: 20,
      spaces: 5,
      icon: "bi bi-bicycle",
    },
  ];
  
  // module.exports = lessons;
  